add user model
SPS-2020-Team-15/Graminsta pull request #1
Opened 2020-07-27 12:40 UTC by shiyi001

First add the user model as an example.

2020-07-27 12:43 UTC, shiyi001 commented
It seems that the current code does not pass CI. @Time1ess

2020-07-28 01:33 UTC, Time1ess commented
Please refer to the CI details about why your PR fails to build.

https://travis-ci.com/github/SPS-2020-Team-15/Graminsta/builds/177285627

2020-07-28 14:00 UTC, shiyi001 commented
I only added the most basic attributes of the User class. What else do you think can be added? @isabella0428 @hht-hannah @ArianaGu

2020-07-29 03:39 UTC, isabella0428 commented
> I only added the most basic attributes of the User class. What else do you think can be added? @isabella0428 @hht-hannah @ArianaGu

The user ids that the user follows?
And also we talk about timeline during the meeting on Monday. Maybe also maintain a list of post ids of the user's timeline?

2020-07-29 04:19 UTC, Time1ess commented
Personally, I prefer extending the existing User model option, instead of defining our own, otherwise we need to take care a lot of details, like password hashing. PTAL https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#extending-the-existing-user-model

2020-07-29 04:21 UTC, Time1ess commented
To anwser @isabella0428 's question, we can start with a MVP one, and add fields one by one. But yes, we do need some
```
   following_users = models.ManyToManyField(..., reverse_name = 'xxx')
```

later

2020-07-29 04:23 UTC, Time1ess commented
To be more specific, we can have one `UserInfo` model

```
class UserInfo(models.Model):
  user = models.OneToOneField(User, xxx)
  age = ...
  gender = ...
  following_users = ...
  ...
```

2020-07-29 06:35 UTC, shiyi001 commented
> To be more specific, we can have one `UserInfo` model
> 
> ```
> class UserInfo(models.Model):
>   user = models.OneToOneField(User, xxx)
>   age = ...
>   gender = ...
>   following_users = ...
>   ...
> ```

I have rewritten the code as suggested.

2020-07-29 09:24 UTC, Time1ess requested changes
I'd suggest to name this app as `core` or `auth` instead of `user`.

2020-07-29 09:24 UTC, Time1ess commented on backend/graminsta/user/models.py
> +    reg_time = models.DateTimeField(auto_now=True)
I think Django user model already have this field.

See also: https://docs.djangoproject.com/en/3.0/ref/contrib/auth/#django.contrib.auth.models.User.date_joined

2020-07-29 09:24 UTC, Time1ess commented on backend/graminsta/user/models.py
> +        related_name="following_users"
This is used to do reverse look up.

For example, suppose `related_name="followed_by"', we have user A, B, C.

* User B is following User A
* User C is following User A
* User C is following User B

So for User C: `user_info_for_user_c.following_users == [User A, User B]`
for User A: `user_info_for_user_a.followed_by == [User B, User C]`

See also: https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.ForeignKey.related_name

2020-07-29 09:24 UTC, Time1ess commented on backend/graminsta/user/models.py
> +        related_name="following_users"
And the follow relationship should be defined on the `User` model, so I'd suggest to define that explicitly.

See also: https://stackoverflow.com/questions/40069192/django-models-database-design-for-user-and-follower

2020-07-29 09:32 UTC, Time1ess requested changes

2020-07-29 09:32 UTC, Time1ess commented on backend/graminsta/user/models.py
> +        related_name="following_users"
And it looks like the follow/followed by relationship is tightly coupled with the `Post` app, so maybe define the relationship in that app would be more reasonable.

2020-07-29 13:21 UTC, shiyi001 commented
- Change the name of app into `core` 
- Remove the follow/unfollow relationship.

2020-07-30 02:05 UTC, Time1ess requested changes
Please generate migration files and submit them too, otherwise people will generate migration files on their own, which might make the migration diverge.

2020-07-30 03:36 UTC, Time1ess requested changes
You might need to delete the migration files for the new changes and re-generate them.

2020-07-30 03:36 UTC, Time1ess commented on backend/graminsta/core/models.py
> +    gender = models.CharField(max_length=10)
For enumerable fields, use `choices` instead.

See also: https://code.djangoproject.com/ticket/18062

2020-07-30 03:36 UTC, Time1ess commented on backend/graminsta/core/models.py
> +    age = models.IntegerField()
Nit: `PositiveIntegerField`?

2020-07-30 06:57 UTC, Time1ess submitted a review, later dismissed

2020-07-30 06:57 UTC, Time1ess commented on backend/graminsta/core/models.py
> +    GENDER_CHOICES = [(GENDER_MALE, 'Male'), (GENDER_FEMALE, 'Female')]
Move the definitions of the genders above, before all the `models.xxx` declarations. 

Nit: use Tuple (`GENDER_CHOICES = ((GENDER_MALE, ...))`) for `GENDER_CHOICES`.

2020-07-30 13:01 UTC, isabella0428 approved these changes

2020-07-30 13:28 UTC, ArianaGu approved these changes

2020-07-30 13:28 UTC, merged